### ISSUE TITLE
Could not find function %<>%

### ISSUE THREAD

**Issue by NWPope** [gforge/Gmisc#10]
> install.packages("Gmisc")
> library(Gmisc)
Loading required package: htmlTable
Warning messages:
1: package ‘Gmisc’ was built under R version 3.1.2 
2: package ‘htmlTable’ was built under R version 3.1.2 
> ?htmlTable
starting httpd help server ... done
> output <- matrix(1:4,
+                  ncol=2,
+                  dimnames = list(list("Row 1", "Row 2"),
+                                  list("Column 1", "Column 2")))
> htmlTable(output)
Error in htmlTable.default(output) : could not find function "%<>%"

Updated to 3.1.2 and same issue. Replicated on Mac OSX Mavericks and Windows Server R2 in both base R and Rstudio 098.1091.
Thanks

**Comment by gforge** [comment]
The htmlTable is as of v1.0 dependent on the **magrittr** package. A little strange that it doesn't automatically install, try installing through `install.packages("htmlTable", dependencies = TRUE)`

**Comment by gforge** [comment]
Found that the `%<>%` was added in **magrittr 1.5**. This restraint has been added to the package description.
