### ISSUE TITLE
getDescriptionStatsBy throws error when useNA = "no" options is used.

### ISSUE THREAD

**Issue by nuprofessor** [gforge/Gmisc#11]
getDescriptionStatsBy throws error when useNA = "no" options is used for some variables.

It worked fine in version 0.6.7 but in version 1.0, the warning is that "there is a discrepancy in the number of rows in the total table and the by results: 1 total vs 3 results." I'm expecting 3 in total as well and cannot figure out why total = 1.

**Comment by nuprofessor** [comment]
Error message is copied and pasted below from debugging. 

4 stop("There is an discrepancy in the number of rows in the total table", 
    " and the by results: ", nrow(total_table), " total vs ", 
    nrow(results), " results", "\n Rows total:", paste(rownames(total_table), 
        collapse = ", "), "\n Rows results:", paste(rownames(results),  ... 
3 getDescriptionStatsBy(data01[, varName], data01$redcap_data_access_group.factor, 
    html = TRUE, add_total_col = TRUE, digits = digits, useNA = "no") 
2 getT1Stat("ds_work4pay.factor") 
1 htmlTable(getT1Stat("ds_work4pay.factor"), title = "Currently working at a paid full or part time job (Original)", 
    align = "rrrrr")

**Comment by gforge** [comment]
Unfortunately I can't replicate your error, here is an extended version of the testthat file. One of the examples should be able to replicate your setting:

```r
library(testthat)
set.seed(1)
aa <- factor(sample(c("A", "B"), size = 50, replace = TRUE))
aa[sample(1:50, size = 5)] <- NA
aaa <- factor(sample(1:3, size = 50, replace = TRUE))
aa[aaa == 2 & is.na(aa)] <- "B"
ret <-
  getDescriptionStatsBy(x = aa, by=aaa, html=TRUE)

expect_match(ret["A","2"], sprintf("^%d", table(aa, aaa)["A","2"]),
             info="The value does not seem to match the raw table")
expect_match(ret["B","2"], sprintf("^%d", table(aa, aaa)["B","2"]),
             info="The value does not seem to match the raw table")
expect_match(ret["Missing","2"], "^0")

ret <-
  getDescriptionStatsBy(x = aa, by=aaa, html=TRUE, useNA="no")
expect_match(ret[1,"2"], sprintf("^%d", table(aa, aaa)["A","2"]),
             info="The value does not seem to match the raw table")
expect_equal(nrow(ret), 1)

ret <-
  getDescriptionStatsBy(x = aa, by=aaa, 
                        useNA="no", 
                        prop_fn = describeFactors)
expect_match(ret["A","2"], sprintf("^%d", table(aa, aaa)["A","2"]),
             info="The value does not seem to match the raw table")
expect_match(ret["B","2"], sprintf("^%d", table(aa, aaa)["B","2"]),
             info="The value does not seem to match the raw table")

cont <- rnorm(length(aa))
cont[sample(1:50, size = 5)] <- NA
cont[aaa == 2 & is.na(cont)] <- 0
ret <-
  getDescriptionStatsBy(x = cont, by=aaa, html=TRUE, useNA="no")
expect_equal(nrow(ret), 1)

aa <- factor(sample(LETTERS[1:3], size = 50, replace = TRUE))
aa[sample(1:50, size = 5)] <- NA
aaa <- factor(sample(1:2, size = 50, replace = TRUE))
aa[aaa == 2] <- "B"
ret <-
  getDescriptionStatsBy(x = aa, by=aaa, html=TRUE, useNA="no")
expect_match(ret["A","2"], sprintf("^%d", table(aa, aaa)["A","2"]),
             info="The value does not seem to match the raw table")
expect_match(ret["B","2"], sprintf("^%d", table(aa, aaa)["B","2"]),
             info="The value does not seem to match the raw table")
```

What is the `class(data01$ds_work4pay.factor)` and does it work with other useNA options?

**Comment by nuprofessor** [comment]
class(data01$ds_work4pay.factor) returns "factor". It works when I remove the add_total_col = TRUE (or "first" or "last). I noticed that this error occurs when one of the factor levels is 0 across all the groups.

**Comment by gforge** [comment]
Thanks, the bug has been fixed in both GitHub repos (develop & master)

**Comment by nuprofessor** [comment]
Works beautifully now. Thank you!
