### ISSUE TITLE
header_count cannot accept string option

### ISSUE THREAD

**Issue by rlevitin** [gforge/Gmisc#13]
header_count in getDescriptionStatsBy cannot be a string because of the construct missing(header_count) || !header_count. If it's a string, the latter fails and returns an error "invalid argument type"

**Comment by gforge** [comment]
Header count is intended to be boolean, the function automatically counts the occurrences. Why would you like to add a string?

**Comment by rlevitin** [comment]
The documentation says you can change the default format of the displayed string by using a sprintf style format. Looking at the code, just after where it returns an error, it looks like it checks to see if header_count is a string that contains %s . 

If there is another way to modify the displayed string, I'd love to know how. 

Thank you. 



—
Please forgive my brevity, sent from Mailbox

**Comment by rlevitin** [comment]
This also is probably not the place to post this, but I don't want to make a separate issue for it. For some reason, getDescriptionStatsBy is throwing an error when I try to knit an Rmd html document. If I just manually run all the code blocks from beginning to end, it works without complaints. But as soon as I try to knit the whole thing I get this error:

    You haven't provided an by-value to do the statistics by. This error is most frequently caused by     referencing an old variable name that doesn't exist anymore
    Calls: <Anonymous> ... eval -> mergeDesc -> getT1Stat -> getDescriptionStatsBy
    Execution halted

I have tried explicitly specifying the by= variable and there is no difference. When I run the command directly, I get no complaints. I'm not sure how to narrow down what exactly the problem is.

I'd really appreciate any help!

**Comment by gforge** [comment]
Ahh.... forgot about that feature. It should be fixed now in the develop-branch.

Not sure about your error. It is triggered by the `is.null(by)` and there is nothing magic about it. If you are using the knitr cache you may need to reset that. Start by testing str(your_by_var) before the call and see what it returns.
