### ISSUE TITLE
getDescriptionstatsBy: use_units = 'name' does not work

### ISSUE THREAD

**Issue by pkoki** [gforge/Gmisc#16]
The option use_units = 'name' does not work as documented, probably because of line 467 - 

if(use_units) 

It should be replaced by something like 

if(isTRUE(use_units))

some tests: 
use_units <- TRUE
if(use_units) print('success')
use_units <- FALSE
if(use_units) print('success')
use_units <- 'name'
if(use_units) print('success')
if(isTRUE(use_units)) print('success')

**Comment by gforge** [comment]
Thank you. Fixed in the develop branch (v. 1.3.1)
