### ISSUE TITLE
getDescriptionStatsBy - x character vector

### ISSUE THREAD

**Issue by raredd** [gforge/Gmisc#24]
When `x` is a character this unhelpful error occurs

```
getDescriptionStatsBy(
  as.character(mtcars$am), mtcars$gear,
  show_all_values = TRUE
)

Error in `substr<-`(`*tmp*`, 1, 1, value = character(0)) : 
  replacing substrings in a non-character object
In addition: Warning message:
In if (unique(sapply(t, length)) == 1) name <- sprintf("%s %s",  :
  the condition has length > 1 and only the first element will be used
```

Note the `substr<-` error goes away if `show_all_values = FALSE`. These are easily fixed by `factor(x)`

```
getDescriptionStatsBy(
  factor(as.character(mtcars$am)), mtcars$gear,
  show_all_values = TRUE
)
```

---

The difference is when we get to `t`

```
t <- structure(list(`3` = structure(c("15 (100.0%)", "0 (0.0%)"), .Dim = c(2L, 
1L), .Dimnames = list(c("0", "1"), NULL)), `4` = structure(c("4 (33.3%)", 
"8 (66.7%)"), .Dim = c(2L, 1L), .Dimnames = list(c("0", "1"), 
    NULL)), `5` = structure(c("0 (0.0%)", "5 (100.0%)"), .Dim = c(2L, 
1L), .Dimnames = list(c("0", "1"), NULL))), .Dim = 3L, .Dimnames = structure(list(
    by = c("3", "4", "5")), .Names = "by"), call = by.default(data = x, 
    INDICES = by, FUN = prop_fn, html = html, digits = digits, 
    number_first = numbers_first, useNA = useNA, useNA.digits = useNA.digits, 
    default_ref = default_ref, percentage_sign = percentage_sign), class = "by")

# by: 3
# [,1]         
# 0 "15 (100.0%)"
# 1 "0 (0.0%)"   
# ----------------------------------------------------------------------------- 
#   by: 4
# [,1]       
# 0 "4 (33.3%)"
# 1 "8 (66.7%)"
# ----------------------------------------------------------------------------- 
#   by: 5
# [,1]        
# 0 "0 (0.0%)"  
# 1 "5 (100.0%)"
```

and this line  `if (unique(sapply(t, length)) == 1)` will be `FALSE` since all of `t` are length 2.

If `t` was a character we would get 

```
# by: 3
# [,1]         
# 0 "15 (100.0%)"
# ----------------------------------------------------------------------------- 
#   by: 4
# [,1]       
# 0 "4 (33.3%)"
# 1 "8 (66.7%)"
# ----------------------------------------------------------------------------- 
#   by: 5
# [,1]        
# 1 "5 (100.0%)"
```

and `if (unique(sapply(t, length)) == 1)` would throw that error and the first value would be `TRUE` or `FALSE` depending on the data, so the evaluation of the next line is a crapshoot.

Also the next line assumes that `x` is a factor anyway:

```
name <- sprintf("%s %s", capitalize(levels(x)[default_ref]), 
        tolower(name))
```

---

The easiest fix would be for the user to make sure `x` is a factor before running, but sometimes I forget and new users might not know nor can I find this suggestion explicitly in the docs, and the error doesn't make things immediately clear.

Possible solutions:

  - explicitly state `x` needs to be numeric or a factor

  - coerce character to factor quietly or with a message/warning

  - `if (all(unique(sapply(t, length)) == 1))` might also achieve the same result since the note suggests this line should only be evaluated if we are dealing with one row

**Comment by lemna** [comment]
I don't get this error in either the github develop (1.4.2) or the CRAN version (1.4.1), R version 3.3.2:

```R
> getDescriptionStatsBy(
+     as.character(mtcars$am), mtcars$gear,
+     show_all_values = TRUE
+ )
as.character(mtcars$am) 
  3             4           5           
0 "15 (100.0%)" "4 (33.3%)" "0 (0.0%)"  
1 "0 (0.0%)"    "8 (66.7%)" "5 (100.0%)"

> getDescriptionStatsBy(
+     factor(as.character(mtcars$am)), mtcars$gear,
+     show_all_values = TRUE
+ )
factor(as.character(mtcars$am)) 
  3             4           5           
0 "15 (100.0%)" "4 (33.3%)" "0 (0.0%)"  
1 "0 (0.0%)"    "8 (66.7%)" "5 (100.0%)"
```

**Comment by gforge** [comment]
Thanks for the report. This happens when a value is missing in one of the outcomes. I've submitted a fix to the dev-branch

@lemna - You missed the `show_all_values = FALSE`.
