### ISSUE TITLE
Gmisc

### ISSUE THREAD

**Issue by kulkarnirahul21** [gforge/Gmisc#25]
Am trying to generate a transition plot on a dataset I have.
Dataset has 10 columns. Level1 to Level10. 
Level1 has 21 unique levls of observations, level2 column has 21,level3 has 17, level4 has 15 and finally Level9 has 2 unique levels. All the missing information was given "None" as label.

I dont want to have boxes and arrows pointing to "None". Can you please help me with the code.

This is the code used

transitions <- table(data$Level1,data$Level2) %>%
  getRefClass("Transition")$new(label=c("1st Iteration", "2nd Iteration"))
transitions$box_width = 0.25;
transitions$box_label_cex = 0.7;
transitions$arrow_type = "simple";
transitions$arrow_rez = 300;
table(data$Level2,data$Level3) %>% transitions$addTransitions(label = '3rd Iteration')
table(data$Level3,data$Level4) %>% transitions$addTransitions(label = '4th Iteration')
table(data$Level4,data$Level5) %>% transitions$addTransitions(label = '5th Iteration')
table(data$Level5,data$Level6) %>% transitions$addTransitions(label = '6th Iteration')
table(data$Level6,data$Level7) %>% transitions$addTransitions(label = '7th Iteration')
table(data$Level7,data$Level8) %>% transitions$addTransitions(label = '8th Iteration')
table(data$Level8,data$Level9) %>% transitions$addTransitions(label = '9th Iteration')
transitions$max_lwd <- unit(.05, "npc")
transitions$render()

**Comment by gforge** [comment]
I guess you need to change the input data. I don't think this is a Gmisc issue. I suggest you try StackOverflow with some test data.
