### ISSUE TITLE
getDescriptionStatsBy for proportions with show_all_values = TRUE overrides user-specified function

### ISSUE THREAD

**Issue by lemna** [gforge/Gmisc#26]
Hi Max,

I ran into this when using a custom function for prop_fn. If a user specifies their own function for prop_fn with the show_all_values = TRUE option the user-specified function is overridden by describeFactors(). This is caused by line 272-273 of getDescriptionStatsBy.R (develop branch).

I can do a PR tonight if you are interested.

with kind regards
Peter.

**Comment by gforge** [comment]
Hi Peter,

thanks for the report + fix. Really appreciate it. 

Have a nice summer!
Max
