### ISSUE TITLE
mergeDesc does not consistently show p-values, or places them inconsistently

### ISSUE THREAD

**Issue by lemna** [gforge/Gmisc#32]
There are two issued with `mergeDesc()` in the latest develop version:
1. It discards p-values when the summary consists of more than one line, for example because missing values are shown, and `rgroup` and `n.rgroup` are specified. 
2. p-values for one-line summaries are shown on the summary line instead of on the `rgroup` title line, when `rgroup` and `n.rgroup` are specified. It would look nicer if all p-values were shown on the `rgroup` title line.

Example below:

```R
library(Gmisc)
data("mtcars")
cars_missing <- mtcars
cars_missing$mpg[3] <- NA

# p-values are not displayed when rgroup and n.rgroup are specified
mergeDesc(getDescriptionStatsBy(x = cars_missing$mpg,
                                by = cars_missing$cyl,
                                statistics = TRUE),
          htmlTable_args = list(rgroup = c("Gas"),
                                n.rgroup = 2))

# p-values are displayed when rgroup and n.rgroup are not specified
mergeDesc(getDescriptionStatsBy(x = cars_missing$mpg,
                                by = cars_missing$cyl,
                                statistics = TRUE))

# p-values are displayed for one-line summaries only when rgroup and n.rgroup are specified
# but in the wrong place - they should be on the rgroup title line, not on the summary line
mergeDesc(getDescriptionStatsBy(x = cars_missing$mpg,
                                by = cars_missing$cyl,
                                statistics = TRUE),
          getDescriptionStatsBy(x = cars_missing$disp,
                                by = cars_missing$cyl,
                                statistics = TRUE),
          htmlTable_args = list(rgroup = c("Gas", "Displacement"),
                                n.rgroup = c(2, 1)))

# p-values are displayed for both summaries when rgroup and n.rgroup are not specified
mergeDesc(getDescriptionStatsBy(x = cars_missing$mpg,
                                by = cars_missing$cyl,
                                statistics = TRUE),
          getDescriptionStatsBy(x = cars_missing$disp,
                                by = cars_missing$cyl,
                                statistics = TRUE))
```
### p-values are not displayed when rgroup and n.rgroup are specified
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey;'> </th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>4</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>6</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>8</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>P-value</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='5' style='font-weight: 900;'>Gas</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;Mean (SD)</td>
<td style='text-align: center;'>27.1 (&plusmn;4.6)</td>
<td style='text-align: center;'>19.7 (&plusmn;1.5)</td>
<td style='text-align: center;'>15.1 (&plusmn;2.6)</td>
<td style='text-align: center;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;Missing</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>1 (9.1%)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>0 (0%)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>0 (0%)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'></td>
</tr>
</tbody>
</table>
 
### p-values are displayed when rgroup and n.rgroup are not specified
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey;'> </th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>4</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>6</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>8</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>P-value</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='4' style=''>cars_missing$mpg</td>
<td style='text-align: center;'>&lt; 0.0001</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;Mean (SD)</td>
<td style='text-align: center;'>27.1 (&plusmn;4.6)</td>
<td style='text-align: center;'>19.7 (&plusmn;1.5)</td>
<td style='text-align: center;'>15.1 (&plusmn;2.6)</td>
<td style='text-align: center;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;Missing</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>1 (9.1%)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>0 (0%)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>0 (0%)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'></td>
</tr>
</tbody>
</table>
 
### p-values are displayed for one-line summaries only when rgroup and n.rgroup are specified, but in the wrong place - they should be on the rgroup title line, not on the summary line
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey;'> </th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>4</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>6</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>8</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>P-value</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='5' style='font-weight: 900;'>Gas</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;Mean (SD)</td>
<td style='text-align: center;'>27.1 (&plusmn;4.6)</td>
<td style='text-align: center;'>19.7 (&plusmn;1.5)</td>
<td style='text-align: center;'>15.1 (&plusmn;2.6)</td>
<td style='text-align: center;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;Missing</td>
<td style='text-align: center;'>1 (9.1%)</td>
<td style='text-align: center;'>0 (0%)</td>
<td style='text-align: center;'>0 (0%)</td>
<td style='text-align: center;'></td>
</tr> 
<tr><td colspan='5' style='font-weight: 900;'>Displacement</td></tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>&nbsp;&nbsp;cars_missing$disp</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>105.1 (&plusmn;26.9)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>183.3 (&plusmn;41.6)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>353.1 (&plusmn;67.8)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>&lt; 0.0001</td>
</tr>
</tbody>
</table>
 
### p-values are displayed for both summaries when rgroup and n.rgroup are not specified
<table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
<thead>
<tr>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey;'> </th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>4</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>6</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>8</th>
<th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>P-value</th>
</tr>
</thead>
<tbody> 
<tr><td colspan='4' style=''>cars_missing$mpg</td>
<td style='text-align: center;'>&lt; 0.0001</td></tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;Mean (SD)</td>
<td style='text-align: center;'>27.1 (&plusmn;4.6)</td>
<td style='text-align: center;'>19.7 (&plusmn;1.5)</td>
<td style='text-align: center;'>15.1 (&plusmn;2.6)</td>
<td style='text-align: center;'></td>
</tr>
<tr>
<td style='text-align: left;'>&nbsp;&nbsp;Missing</td>
<td style='text-align: center;'>1 (9.1%)</td>
<td style='text-align: center;'>0 (0%)</td>
<td style='text-align: center;'>0 (0%)</td>
<td style='text-align: center;'></td>
</tr>
<tr>
<td style='border-bottom: 2px solid grey; text-align: left;'>cars_missing$disp</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>105.1 (&plusmn;26.9)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>183.3 (&plusmn;41.6)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>353.1 (&plusmn;67.8)</td>
<td style='border-bottom: 2px solid grey; text-align: center;'>&lt; 0.0001</td>
</tr>
</tbody>
</table>

**Comment by gforge** [comment]
Thanks! Awesome as always!
