### ISSUE TITLE
statistics.sig_lim

### ISSUE THREAD

**Issue by AlineTalhouk** [gforge/Gmisc#35]
When using a statistical sig limit threshold for a continuous variable in getDescriptioStatsBy, The Pvalue shows as  &lt; 0.0001  instead of <0.0001. Same with the &plusmn, probably indicating bugs in the html code

```
getDescriptionStatsBy(mtcars$wt, by=mtcars$am, statistics = TRUE) %>% htmlTable(.)
```

**Comment by lemna** [comment]
Hi,

`htmlTable()` gained an argument to escape html code. Try:

```r
getDescriptionStatsBy(mtcars$wt, by = mtcars$am, statistics = TRUE) %>%
  htmlTable(escape.html = FALSE)
```

@gforge, it seems that there are some unintended consequences to this change. Would you prefer to change the default value for escape.html, adapt the associated functions in Gmisc or leave as is? I'd be happy to submit some patches.

**Comment by gforge** [comment]
@lemna - yeah, there are some unintended side-effects. My original thought was actually to allow html entities, as part of the benefit is that it in contrast to kable and other solutions allow you to use all the html tricks out there. I'm in favor of changing `escape.html` to default to false. Can you PR it?

**Comment by AlineTalhouk** [comment]
@lemna Thank you that resolves it for me! What was strange is that this was only an issue for continuous variables and not categorical.
