### ISSUE TITLE
CRAN issue - readonly filesystem

### ISSUE THREAD

**Issue by gforge** [gforge/Gmisc#36]
Message from Kurt Hornik:

> These all show check problems on the Debian check systems caused by
> attempts to write to the user library to which all packages get
> installed before checking (and which now is remounted read-only for
> checking).
> 
> Having package code which is run as part of the checks and attempts to
> write to the user library violates the CRAN Policy's
> 
>   Packages should not write in the user’s home filespace (including
>   clipboards), nor anywhere else on the file system apart from the R
>   session’s temporary directory (or during installation in the location
>   pointed to by TMPDIR: and such usage should be cleaned up).
> 
> Hence, please update your package(s) as quickly as possible to no longer
> (attempt to) write to the user library (including, of course, the
> location where the package itself was installed to).
>

**Comment by lemna** [comment]
How would you check for this? R cmd check --as-cran does not show any error and it builds fine on travis. Some things are written to TMPDIR but they seem to be cleaned up afterwards.

**Comment by gforge** [comment]
Yeah, the folks at CRAN certainly don't make it easy for us. Deleting those tests could be a last resort, it feels wrong though....

**Comment by lemna** [comment]
Do you know whether the problem is in the examples, in the vignettes or in the tests?

**Comment by gforge** [comment]
There is one place where I use `tempfile`: https://github.com/gforge/Gmisc/blob/c1a47566063b97ae1c8b9d795e2864fa9f06f40d/R/docx_document.R#L83

I think this is causing the issue. Hard to know with the little information provided in the report. In the list of failing packages was also knitr, perhaps we can piggy-back on Yihui's expertice once he fixes the issue: https://github.com/yihui/knitr/search?utf8=%E2%9C%93&q=tempfile&type=
