### ISSUE TITLE
transitionPlot without shadow?

### ISSUE THREAD

**Issue by duleise** [gforge/Gmisc#37]
`transitionPlot.R` is cool. I prefer it to _original_ Sankey, in which sometimes the bands are not readable.
I wonder could it be possible to control the shadow of the boxes? I personally like my plots to be minimalist, or without 3D effect.
Thanks.

**Comment by gforge** [comment]
Pushed a new version to the develop branch - checkout the skip_shadows argument for the Transition-class.

**Comment by duleise** [comment]
Works as magic.
Thank you.
