### ISSUE TITLE
Plots drawn on top of one another.

### ISSUE THREAD

**Issue by V-Sher** [gforge/Gmisc#42]
I am practicing using the code on the project page https://cran.r-project.org/web/packages/Gmisc/vignettes/transitionPlot.html and I found that anytime I make a small change to the parameters and try plotting the transition plot again, it overlays on previous one instead of creating a new plot on a new pane (see screenshot attached). I doubt this is a problem with Rstudio or R version as I tried plotting multiple plots using ggplot package and some base R plotting functions and each of them come up in a new plot pane.

In case you need it:
Rstudio: Version 1.1.453
R 3.5.1 GUI 1.70 El Capitan build (7543)
MAC OS High Sierra Version 10.13.1

![Screen Shot 2019-06-14 at 11 52 53 AM](https://user-images.githubusercontent.com/18684411/59531539-141c8800-8e9b-11e9-86b0-f69aa7e0c309.png)

**Comment by gforge** [comment]
This is a grid feature. See the `new_page` argument
