### ISSUE TITLE
Auto change box height and width

### ISSUE THREAD

**Issue by adayim** [gforge/Gmisc#56]
Hi,

**Background**
I am using this package to create consort diagram. If there are lots of box nodes, the plot will be cropped. Like some times I get negative y value for the box if I want to align the boxes to avoid any overlaps. 

**Issue**
One solution I find is to change the text size by changing the cex to lower value. But the box size stayed the same. I realized that the `grobHeight(txt)` and `grobWidth(txt)` will return `1grobheight` and `1grobwidth`.  The box size actually stayed the same. 

**Possible solution**
If I change it to `convertUnit(grobHeight(txt), "mm")` and `convertUnit(grobWidth(txt), "mm")` the box size will change automatically. 

Can this be changed? Or should I submit a pull request? Many thanks.

Best,
Alimu

**Comment by gforge** [comment]
I'm not sure I'm following. Do you have a reproducible example?

**Comment by adayim** [comment]
Sorry for not providing an example. If there are lots of boxes, the one at the bottom will be cropped. Below is the code:
```r
library(grid)
library(Gmisc)

options(boxGrobTxt = gpar(color = "black", cex = 1), 
             connectGrobArrow = arrow(length = unit(0.1, "inches"), type = "closed"))
# Define box
node1 <- boxGrob("Population (n=300)", y = 0.9)
side_node1 <- boxGrob("Excluded (n=15)\n:\u2022 MRI not collected (n=3)\n\u2022 Tissues not collected (n=4)\n\u2022 Other (n=8)",
                      x = 0.63, y = 0.79, just = "left")

node2 <- boxGrob("Induction (n=285)", x = 0.5, y = 0.68)
side_node2 <- boxGrob("Excluded (n=18)\n:\u2022 Blood sample not collected (n=4)\n\u2022 Dead (n=4)\n\u2022 Other (n=10)",
                      x = 0.65, y = 0.57, just = "left")

node3 <- boxGrob("Randomized (n=267)", x = 0.5, y = 0.46)
node1_left <- boxGrob("Conc (n=142)", x = 0.25, y = 0.36)
node1_right <- boxGrob("Seq (n=125)", x = 0.75, y = 0.36)

node2_left <- boxGrob("Lost to followup (n=30)\n:\u2022 Death (n=6)\n\u2022 Discontinued (n=12)\n\u2022 Withdraw (n=4)\n\u2022 Other (n=8)",
                      just = "left", x = 0.25, y = 0.21)
node2_right <- boxGrob("Lost to followup (n=23)\n:\u2022 Death (n=5)\n\u2022 Discontinued (n=6)\n\u2022 Withdraw (n=6)\n\u2022 Other (n=6)",
                       just = "left", x = 0.75, y = 0.21)


node3_left <- boxGrob("Final analysis (n=97)\n:\u2022 Non-evaluable (n=7)\n\u2022 Protocol deviation (n=8)",
                      just = "left", x = 0.25, y = 0.05)
node3_right <- boxGrob("Final analysis (n=92)\n:\u2022 Non-evaluable (n=6)\n\u2022 Protocol deviation (n=4)",
                       just = "left", x = 0.75, y = 0.05)

# Draw and connect
grid.newpage()
node1
side_node1
connectGrob(node1, side_node1, type = "L")
node2
connectGrob(node1, node2, type = "N")
side_node2
connectGrob(node2, side_node2, type = "L")
node3
connectGrob(node2, node3, type = "N")
node1_left
node1_right
connectGrob(node3, node1_left, type = "N")
connectGrob(node3, node1_right, type = "N")
node2_left
node2_right
connectGrob(node1_left, node2_left, type = "N")
connectGrob(node1_right, node2_right, type = "N")
node3_left
node3_right
connectGrob(node2_left, node3_left, type = "N")
connectGrob(node2_right, node3_right, type = "N")
```
Aligning for those boxes take a long time, but the bottom of the plot is cropped. So I changed the options to the following to decrease the font size:
```r
options(boxGrobTxt = gpar(color = "black", cex = 0.8),
             connectGrobArrow = arrow(length = unit(0.1, "inches"), type = "closed"))
```
After changing the option `cex` I need to re-align everything to fit the page. then I developed a function to cope with this kind of standard flow chart.  But the change in padding between text and box does not follow `cex`, result in large padding between box and text. Is it possible to let the padding change accordingly with `cex`? So I can decrease the `cex` to fit lots of boxes, let's say an amount of 2 times of boxes compared to the example. 

P.S: I can't find an option for choosing the `boxGrob` from `rectGrob` and `roundrectGrob`. Is it possible to make this happen?

**Comment by gforge** [comment]
Doesn't this solve your issues?

```R
verts <- spreadVertical(node1, node2, node3, node1_left, node2_left)
node1_right <- alignVertical(verts[[4]], node1_right)
node2_right <- alignVertical(verts[[5]], node2_right)

# Draw and connect
grid.newpage()
verts
node1_right
node2_right
side_node1 <- boxGrob("Excluded (n=15)\n:\u2022 MRI not collected (n=3)\n\u2022 Tissues not collected (n=4)\n\u2022 Other (n=8)",
                      x = 0.9, 
                      y = coords(verts[[1]])$bottom - distance(verts[[1]], verts[[2]], type = "vertical", half = TRUE),
                      just = "left",
                      bjust = "right")
side_node1
connectGrob(verts[[1]], side_node1, type = "L")
connectGrob(verts[[1]], verts[[2]], type = "v")

side_node2 <- boxGrob("Excluded (n=18)\n:\u2022 Blood sample not collected (n=4)\n\u2022 Dead (n=4)\n\u2022 Other (n=10)",
                      x = 0.9, 
                      y = coords(verts[[2]])$bottom - distance(verts[[2]], verts[[3]], type = "vertical", half = TRUE),
                      just = "left",
                      bjust = "right")
side_node2
connectGrob(verts[[2]], side_node2, type = "L")
connectGrob(verts[[2]], verts[[3]], type = "v")
connectGrob(verts[[3]], verts[[4]], type = "N")
connectGrob(verts[[3]], node1_right[[1]], type = "N")
connectGrob(verts[[4]], verts[[5]], type = "v")
connectGrob(node1_right[[1]], node2_right[[1]], type = "v")
```

**Comment by adayim** [comment]
You are quick. This will have an overlap between the side nodes. I think you missed the final `node3_left` and `node3_right`. Still the problem is what if there are more boxes vertically. And the height of the left and right box might not always the same. What I am really interested is:
1.  If the padding will change according to the `cex` settings? Maybe multiply the padding with `cex`?
2. Can you add a parameters to `boxGrob`, so user can choose from `rectGrob` and `roundrectGrob`.

**Comment by gforge** [comment]
1. I've never played around with `cex` so I haven't seen the issue. Post a separate issue that clearly explains the problem with example, my thought is that the `cex` should be handled automatically by the `grid`-package.
2. Sure, although this should probably also have a separate issue. Probably a good idea to have a decorator function that draws the box independent so that it can be swapped as needed. I don't have the time to implement it though, a PR is though welcome.
3. Nope - ggplot solves a completely different problem in my mind and I see no clear benefit merging them. I have also absolutely no clue on even where to start, last time I looked at the ggplot code it was doing too much magic for me to fully understand...

**Comment by adayim** [comment]
Sorry for the delay. I will submit a PR.
