### ISSUE TITLE
Add box decorator

### ISSUE THREAD

**Issue by adayim** [gforge/Gmisc#57]
## Problem:
As discussed in the other issue #56 . The `boxGrob` function only draw round cornered rectangle, add an option to allow selection of the rectangle shape.
## Solution:
Add a parameters to `boxGrob`, so user can choose from `rectGrob` and `roundrectGrob`.

**Comment by gforge** [comment]
I think the solution should be that we have a function in the parameters that draws the box and accepts the same parameters as today's box. Not sure if the name should be decoratorFn or something simple as boxFn.

**Comment by adayim** [comment]
So you mean pass the name of the grob function?

**Comment by gforge** [comment]
Not the name but the actual function and the simply call it with `do.call`

**Comment by adayim** [comment]
This should work now.
