### ISSUE TITLE
Should DESCRIPTION state R 4.1.0 is required given use of native pipe

### ISSUE THREAD

**Issue by remlapmot** [gforge/Gmisc#65]
Thanks for a great package.

Given the native pipe, `|>`, is now used in several places in the code, do you need to update the `DESCRIPTION` file to reflect the version of R where that was introduced, i.e., 
```
Depends:
    R (>= 3.2.0),
```
needs to be bumped up to
```
Depends:
    R (>= 4.1.0),
```

**Comment by gforge** [comment]
Thanks, and sorry for the late fix. I've been on parental leave and have had limited time on my hands.
