### ISSUE TITLE
Bug in prData2Plot function? (getSvdMostInfluential.R) 

### ISSUE THREAD

**Issue by okingfisher** [gforge/Gmisc#66]
I checked the getSvdMostInfluential() function after getting different results in the data output and the plot.
I found that it calls Gmisc:::prData2Plot(). It defines a function within a lapply for building the plot x-axis labels (line 128 of getSvdMostInfluential.R).
I believe that the line:
      ret <- paste(c(varnames[1:(prGetMaxNo2Print() - 1)],
                     sprintf("+ %d other", length(x) + 1 - prGetMaxNo2Print())), collapse = "\n")
should be:
      ret <- paste(c(varnames[x[1:(prGetMaxNo2Print() - 1)]],
                     sprintf("+ %d other", length(x) + 1 - prGetMaxNo2Print())), collapse = "\n")
Otherwise, it just prints the variable names in order, not the ones corresponding to that group.
Greetings!

**Comment by gforge** [comment]
Thanks! Great that you found this, I've actually not used the function that much but this seems reasonable. I'm having issues running the example due to `Error in La.svd(x, nu, nv) : error code 14 from Lapack routine 'dgesdd'` - I'll try to install a newer LAPACK abd see if this helps.

**Comment by gforge** [comment]
Solved

**Comment by okingfisher** [comment]
Thank you, great work!
