### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by anneleenders** [gforge/Gmisc#67]
Dear Max, 

I'm trying to install your package un Rstudio using the GUI and searching it in the search box. I cannot find it in the CRAN repository unfortunately. Also when downloading it from here (https://cran.r-project.org/web/packages/Gmisc/index.html) and then installing it from a file on my computer, I get errors. 
How do I install your package from the CRAN repository? 

Best, 
Anne

**Comment by gforge** [comment]
I use install.packages("Gmisc")

**Comment by anneleenders** [comment]
Ah, now I see what my problem is. I get the following error: package ‘Gmisc’ is not available (for R version 4.0.2)
